//@version=6
indicator("XAU ARY LITE V1.1", overlay=true)

h1Ema20 = request.security(syminfo.tickerid, "60", ta.ema(close, 20))
h1Ema50 = request.security(syminfo.tickerid, "60", ta.ema(close, 50))

trendBull = h1Ema20 > h1Ema50
trendBear = h1Ema20 < h1Ema50

ema20 = ta.ema(close, 20)
ema50 = ta.ema(close, 50)

plot(ema20)
plot(ema50)

atr = ta.atr(14)

buySignal = trendBull and ta.crossover(ema20, ema50)
sellSignal = trendBear and ta.crossunder(ema20, ema50)

if buySignal
    label.new(bar_index, low, "BUY")

if sellSignal
    label.new(bar_index, high, "SELL")
